-- Q-S.A.M recovery schema generated from current frontend usage.
-- Execute in Supabase SQL Editor on your new project.

begin;

create extension if not exists pgcrypto;

-- Keep existing users table compatible with current pages.
alter table if exists public.users
    add column if not exists email text;

create index if not exists idx_users_email_lower
    on public.users ((lower(email)));

-- Resume applications
create table if not exists public.resume_applications (
    id bigint generated by default as identity primary key,
    full_name text not null default '',
    age integer,
    gender text,
    location text,
    contact text,
    meme text,
    attributes text[] not null default '{}',
    ability text not null default '无',
    other text,
    department text,
    submission_date timestamptz not null default now(),
    status text not null default 'pending',
    applicant_type text not null default 'guest',

    reviewer text,
    review_date timestamptz,
    review_reason text,

    final_status text,
    final_reviewer text,
    final_review_date timestamptz,
    final_review_reason text,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_resume_created_at
    on public.resume_applications (created_at desc);
create index if not exists idx_resume_status
    on public.resume_applications (status);
create index if not exists idx_resume_final_status
    on public.resume_applications (final_status);

-- Tasks
create table if not exists public.tasks (
    id text primary key,
    name text not null,
    title text generated always as (name) stored,
    type text not null,
    time_limit integer not null check (time_limit between 1 and 365),
    description text not null default '无描述',
    difficulty text not null default '暂无',
    status text not null default '未接取',
    created_by text not null default '未知',
    assigned_team text not null default '未分配',
    assigned_member text not null default '未分配',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_tasks_created_at
    on public.tasks (created_at desc);
create index if not exists idx_tasks_status
    on public.tasks (status);

-- Subjects
create table if not exists public.subjects (
    id bigint generated by default as identity primary key,
    subject_code text not null,
    subject_name text not null,
    generation integer,
    creation_basis text,
    meme_type text,
    attribute text,
    description text,
    status text not null default 'active',
    created_by text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_subject_code unique (subject_code)
);

create index if not exists idx_subjects_created_at
    on public.subjects (created_at desc);
create index if not exists idx_subjects_status
    on public.subjects (status);

-- Subject details (1:1 with subjects)
create table if not exists public.subject_details (
    id bigint generated by default as identity primary key,
    subject_id bigint not null,
    appearance text,
    abilities text,
    weaknesses text,
    containment_procedures text,
    notes text,
    location text,
    danger_level text not null default 'safe',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_subject_details_subject
        foreign key (subject_id) references public.subjects(id) on delete cascade,
    constraint uq_subject_details_subject_id unique (subject_id)
);

-- Rift monsters
create table if not exists public.rift_monsters (
    id uuid primary key default gen_random_uuid(),
    local_id text not null,
    name text not null,
    title text generated always as (name) stored,
    region text,
    frequency text,
    level text,
    weaknesses jsonb not null default '[]'::jsonb,
    resistances jsonb not null default '[]'::jsonb,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_rift_monsters_local_id unique (local_id)
);

create index if not exists idx_rift_monsters_created_at
    on public.rift_monsters (created_at desc);

-- Generic updated_at trigger
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_resume_applications_updated_at on public.resume_applications;
create trigger trg_resume_applications_updated_at
before update on public.resume_applications
for each row execute function public.touch_updated_at();

drop trigger if exists trg_tasks_updated_at on public.tasks;
create trigger trg_tasks_updated_at
before update on public.tasks
for each row execute function public.touch_updated_at();

drop trigger if exists trg_subjects_updated_at on public.subjects;
create trigger trg_subjects_updated_at
before update on public.subjects
for each row execute function public.touch_updated_at();

drop trigger if exists trg_subject_details_updated_at on public.subject_details;
create trigger trg_subject_details_updated_at
before update on public.subject_details
for each row execute function public.touch_updated_at();

drop trigger if exists trg_rift_monsters_updated_at on public.rift_monsters;
create trigger trg_rift_monsters_updated_at
before update on public.rift_monsters
for each row execute function public.touch_updated_at();

-- Disable RLS for quick recovery compatibility with current front-end anon access.
alter table if exists public.users disable row level security;
alter table if exists public.member_details disable row level security;
alter table if exists public.resume_applications disable row level security;
alter table if exists public.tasks disable row level security;
alter table if exists public.subjects disable row level security;
alter table if exists public.subject_details disable row level security;
alter table if exists public.rift_monsters disable row level security;

-- Grant CRUD to common Supabase API roles.
grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on table
    public.users,
    public.member_details,
    public.resume_applications,
    public.tasks,
    public.subjects,
    public.subject_details,
    public.rift_monsters
to anon, authenticated, service_role;

grant usage, select on all sequences in schema public to anon, authenticated, service_role;

commit;
